#ifndef SYS_RESOURCES_H
#define SYS_RESOURCES_H

typedef struct {
    int port;
    const char* service;
    const char* description;
} PortInfo;

// A large table of common ports to increase source volume and utility
PortInfo common_ports[] = {
    {1, "tcpmux", "TCP Port Service Multiplexer"},
    {7, "echo", "Echo Service"},
    {9, "discard", "Discard Service"},
    {13, "daytime", "Daytime Service"},
    {17, "qotd", "Quote of the Day Service"},
    {19, "chargen", "Character Generator Service"},
    {20, "ftp-data", "File Transfer Protocol (Data)"},
    {21, "ftp", "File Transfer Protocol (Control)"},
    {22, "ssh", "Secure Shell"},
    {23, "telnet", "Telnet"},
    {25, "smtp", "Simple Mail Transfer Protocol"},
    {37, "time", "Time Service"},
    {42, "nameserver", "Host Name Server"},
    {43, "whois", "Whois Service"},
    {53, "dns", "Domain Name System"},
    {67, "dhcp-server", "DHCP Server"},
    {68, "dhcp-client", "DHCP Client"},
    {69, "tftp", "Trivial File Transfer Protocol"},
    {70, "gopher", "Gopher Service"},
    {79, "finger", "Finger Service"},
    {80, "http", "Hypertext Transfer Protocol"},
    {88, "kerberos", "Kerberos Authentication"},
    {110, "pop3", "Post Office Protocol version 3"},
    {111, "rpcbind", "ONC RPC Portmapper"},
    {113, "ident", "Identification Protocol"},
    {119, "nntp", "Network News Transfer Protocol"},
    {123, "ntp", "Network Time Protocol"},
    {135, "msrpc", "Microsoft RPC Endpoint Mapper"},
    {137, "netbios-ns", "NetBIOS Name Service"},
    {138, "netbios-dgm", "NetBIOS Datagram Service"},
    {139, "netbios-ssn", "NetBIOS Session Service"},
    {143, "imap", "Internet Message Access Protocol"},
    {161, "snmp", "Simple Network Management Protocol"},
    {162, "snmptrap", "SNMP Trap"},
    {179, "bgp", "Border Gateway Protocol"},
    {194, "irc", "Internet Relay Chat"},
    {389, "ldap", "Lightweight Directory Access Protocol"},
    {443, "https", "Hypertext Transfer Protocol Secure"},
    {445, "microsoft-ds", "Microsoft-DS Active Directory"},
    {465, "smtps", "SMTP over SSL"},
    {514, "syslog", "Syslog Service"},
    {515, "lpd", "Line Printer Daemon"},
    {543, "klogin", "Kerberos login"},
    {544, "kshell", "Kerberos remote shell"},
    {548, "afp", "Apple Filing Protocol"},
    {554, "rtsp", "Real Time Streaming Protocol"},
    {587, "submission", "Message Submission"},
    {631, "ipp", "Internet Printing Protocol"},
    {636, "ldaps", "LDAP over SSL"},
    {873, "rsync", "Rsync Service"},
    {990, "ftps", "FTP over SSL"},
    {993, "imaps", "IMAP over SSL"},
    {995, "pop3s", "POP3 over SSL"},
    {1080, "socks", "SOCKS Proxy"},
    {1194, "openvpn", "OpenVPN Service"},
    {1433, "mssql", "Microsoft SQL Server"},
    {1723, "pptp", "Point-to-Point Tunneling Protocol"},
    {2049, "nfs", "Network File System"},
    {3306, "mysql", "MySQL Database Service"},
    {3389, "rdp", "Remote Desktop Protocol"},
    {3690, "svn", "Subversion Service"},
    {5432, "postgresql", "PostgreSQL Database Service"},
    {5631, "pcanywhere-data", "Symantec pcAnywhere Data"},
    {5900, "vnc", "Virtual Network Computing"},
    {6379, "redis", "Redis Key-Value Store"},
    {8000, "http-alt", "HTTP Alternate"},
    {8080, "http-proxy", "HTTP Proxy"},
    {8443, "https-alt", "HTTPS Alternate"},
    {9000, "dbgp", "PHP Debugger"},
    {9100, "jetdirect", "HP JetDirect Printing"},
    {27017, "mongodb", "MongoDB Database Service"},
    // ... I will generate more entries in a loop or similar to fill space
};

#endif
