package com.butler.android

import android.content.BroadcastReceiver
import android.content.Context
import android.content.Intent
import android.content.IntentFilter
import android.os.BatteryManager
import android.os.Bundle
import android.view.View
import android.view.WindowManager
import android.webkit.JavascriptInterface
import android.webkit.WebMessage
import android.webkit.WebMessagePort
import android.webkit.WebResourceRequest
import android.webkit.WebResourceResponse
import android.webkit.WebView
import android.webkit.WebViewClient
import androidx.appcompat.app.AppCompatActivity
import androidx.webkit.WebViewAssetLoader
import com.chaquo.python.Python
import com.chaquo.python.PyObject
import android.util.Log
import org.json.JSONObject
import java.io.File

// Import the Go-Mobile mobile package (generated by gomobile bind)
import mobile.Mobile
import mobile.Runner
import mobile.ButlerEventListener

class MainActivity : AppCompatActivity() {

    private lateinit var webView: WebView
    private var butlerModule: PyObject? = null
    private lateinit var assetLoader: WebViewAssetLoader
    private var kernelRunner: Runner? = null
    private var nativePort: WebMessagePort? = null
    private var batteryReceiver: BroadcastReceiver? = null
    private val skillExecutor = java.util.concurrent.Executors.newFixedThreadPool(4)
    private var activeModelHelper: LlmModelHelper? = null
    private lateinit var downloadRepository: DownloadRepository

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        // 1. Force Hardware Acceleration
        window.setFlags(
            WindowManager.LayoutParams.FLAG_HARDWARE_ACCELERATED,
            WindowManager.LayoutParams.FLAG_HARDWARE_ACCELERATED
        )

        // Start Foreground Service
        val serviceIntent = Intent(this, ButlerForegroundService::class.java)
        if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.O) {
            startForegroundService(serviceIntent)
        } else {
            startService(serviceIntent)
        }

        // Initialize Python & SkillManager
        val py = Python.getInstance()
        butlerModule = py.getModule("butler_android")
        butlerModule?.callAttr("initialize", filesDir.absolutePath)

        // Initialize Model Download Repository
        downloadRepository = DownloadRepository(this)

        // Setup Asset Loader
        assetLoader = WebViewAssetLoader.Builder()
            .addPathHandler("/assets/", WebViewAssetLoader.AssetsPathHandler(this))
            .addPathHandler("/skills/", WebViewAssetLoader.InternalStoragePathHandler(this, File(filesDir, "skills")))
            .build()

        // Setup WebView
        webView = WebView(this)
        setContentView(webView)
        webView.setLayerType(View.LAYER_TYPE_HARDWARE, null)

        val settings = webView.settings
        settings.javaScriptEnabled = true
        settings.domStorageEnabled = true
        settings.allowFileAccess = true

        webView.addJavascriptInterface(ButlerNativeBridge(), "ButlerNativeBridge")

        webView.webViewClient = object : WebViewClient() {
            override fun shouldInterceptRequest(view: WebView?, request: WebResourceRequest): WebResourceResponse? {
                return assetLoader.shouldInterceptRequest(request.url)
            }

            override fun onPageFinished(view: WebView?, url: String?) {
                super.onPageFinished(view, url)
                setupWebMessageChannel()
            }
        }

        // 2. Initialize and Start Go-Mobile Kernel
        startGoKernel()

        webView.loadUrl("https://appassets.androidplatform.net/assets/www/index.html")

        // 3. Register Battery/Thermal Monitor
        registerBatteryMonitor()
    }

    private fun setupWebMessageChannel() {
        if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.M) {
            val channel = webView.createWebMessageChannel()
            nativePort = channel[0]
            nativePort?.setWebMessageCallback(object : WebMessagePort.WebMessageCallback() {
                override fun onMessage(port: WebMessagePort?, message: WebMessage?) {
                    Log.d("ButlerBridge", "Received from Web: ${message?.data}")
                }
            })
            // Transfer port[1] to the web side
            webView.postWebMessage(WebMessage("init_bridge", arrayOf(channel[1])), android.net.Uri.parse("https://appassets.androidplatform.net"))
            Log.i("MainActivity", "WebMessagePort Channel Established")
        }
    }

    private fun registerBatteryMonitor() {
        val filter = IntentFilter(Intent.ACTION_BATTERY_CHANGED)
        batteryReceiver = object : BroadcastReceiver() {
            override fun onReceive(context: Context?, intent: Intent?) {
                val level = intent?.getIntExtra(BatteryManager.EXTRA_LEVEL, -1) ?: -1
                val scale = intent?.getIntExtra(BatteryManager.EXTRA_SCALE, -1) ?: -1
                val batteryPct = (level * 100 / scale.toFloat()).toInt()
                val temperature = (intent?.getIntExtra(BatteryManager.EXTRA_TEMPERATURE, 0) ?: 0) / 10.0
                val status = intent?.getIntExtra(BatteryManager.EXTRA_STATUS, -1) ?: -1
                val isCharging = status == BatteryManager.BATTERY_STATUS_CHARGING || status == BatteryManager.BATTERY_STATUS_FULL

                kernelRunner?.updateSystemState(temperature, batteryPct, isCharging)
            }
        }
        registerReceiver(batteryReceiver, filter)
    }

    private fun startGoKernel() {
        try {
            kernelRunner = Mobile.newRunner()

            val config = JSONObject().apply {
                put("server_url", "ws://192.168.1.100:8000/ws/butler") // Example config
                put("token", "BUTLER_SECRET_2026")
                put("id", "android_node_" + android.os.Build.MODEL)
            }

            kernelRunner?.start(config.toString(), object : ButlerEventListener {
                override fun OnStatusUpdate(status: String) {
                    Log.i("ButlerKernel", "Status: $status")
                }

                override fun OnLog(message: String) {
                    Log.d("ButlerKernel", "Log: $message")
                }

                override fun OnMetricsUpdate(jsonMetrics: String) {
                    // High-frequency zero-copy injection to WebView via WebMessagePort
                    runOnUiThread {
                        if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.M) {
                            nativePort?.postMessage(WebMessage(jsonMetrics))
                        } else {
                            webView.evaluateJavascript("if(window.StateMatrix) window.StateMatrix.updateFromBackend($jsonMetrics);", null)
                        }

                        // Update Notification with metrics summary
                        try {
                            val metrics = JSONObject(jsonMetrics)
                            val cpu = metrics.optDouble("cpu", 0.0)
                            val throttled = metrics.optBoolean("throttled", false)
                            val serviceIntent = Intent(this@MainActivity, ButlerForegroundService::class.java).apply {
                                putExtra("metrics", "⚡ DRAS: ${if (throttled) "Throttled" else "Healthy"} | CPU: $cpu%")
                            }
                            startService(serviceIntent)
                        } catch (e: Exception) {}
                    }
                }

                override fun OnThrottlingTriggered(active: Boolean) {
                    Log.w("ButlerKernel", "DRAS Throttling Triggered: $active")
                    runOnUiThread {
                        val skillSdk = Python.getInstance().getModule("butler.core.skill_sdk")
                        skillSdk.callAttr("trigger_global_throttling", active)

                        // Push throttling state to UI
                        val msg = JSONObject().apply {
                            put("type", "DRAS")
                            put("active", active)
                        }
                        if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.M) {
                            nativePort?.postMessage(WebMessage(msg.toString()))
                        }
                    }
                }

                override fun OnDrasStateChanged(cpuUsage: Double, throttleActive: Boolean) {
                    Log.w("ButlerKernel", "DRAS State: CPU=$cpuUsage, Throttle=$throttleActive")
                }

                override fun OnClusterDiscovered(deviceName: String, ipAddress: String) {
                    Log.i("ButlerKernel", "Discovered Node: $deviceName at $ipAddress")
                }
            })
            Log.i("MainActivity", "Go Kernel Started Successfully")
        } catch (e: Exception) {
            Log.e("MainActivity", "Failed to start Go Kernel: ${e.message}")
        }
    }

    inner class ButlerNativeBridge {
        @JavascriptInterface
        fun triggerModelDownload(name: String, url: String, fileName: String, version: String, runtimeTypeStr: String, hfToken: String?) {
            runOnUiThread {
                try {
                    val runtimeType = if (runtimeTypeStr == "AICORE") RuntimeType.AICORE else RuntimeType.LITERT_LM
                    val model = Model(name, name, url, 0, fileName, version, true, runtimeType)
                    val uuid = downloadRepository.startModelDownload(model, hfToken)
                    downloadRepository.getDownloadWorkInfo(uuid).observe(this@MainActivity) { workInfo ->
                        if (workInfo != null) {
                            val progress = workInfo.progress.getInt("progress", -1)
                            val state = workInfo.state.name
                            val updateJson = JSONObject().apply {
                                put("type", "MODEL_DOWNLOAD_UPDATE")
                                put("modelName", name)
                                put("progress", progress)
                                put("state", state)
                            }
                            if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.M) {
                                nativePort?.postMessage(WebMessage(updateJson.toString()))
                            }
                        }
                    }
                } catch (e: Exception) {
                    Log.e("MainActivity", "Failed to start download via bridge: ${e.message}")
                }
            }
        }

        @JavascriptInterface
        fun initializeModel(name: String, url: String, fileName: String, version: String, runtimeTypeStr: String) {
            runOnUiThread {
                try {
                    val runtimeType = if (runtimeTypeStr == "AICORE") RuntimeType.AICORE else RuntimeType.LITERT_LM
                    val model = Model(name, name, url, 0, fileName, version, true, runtimeType)

                    // Release any active runtime
                    activeModelHelper?.cleanUp {}

                    val helper: LlmModelHelper = if (runtimeType == RuntimeType.AICORE) {
                        AiCoreModelHelper()
                    } else {
                        LiteRtLlmModelHelper()
                    }
                    activeModelHelper = helper

                    helper.initialize(this@MainActivity, model) { success ->
                        val initStatus = JSONObject().apply {
                            put("type", "MODEL_INIT_STATUS")
                            put("modelName", name)
                            put("success", success)
                        }
                        if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.M) {
                            nativePort?.postMessage(WebMessage(initStatus.toString()))
                        }
                    }
                } catch (e: Exception) {
                    Log.e("MainActivity", "Failed to initialize model: ${e.message}")
                }
            }
        }

        @JavascriptInterface
        fun runModelInference(input: String) {
            val helper = activeModelHelper
            if (helper == null) {
                Log.e("MainActivity", "No active model initialized.")
                return
            }
            helper.runInference(input, emptyList(), object : ResultListener {
                override fun onResult(partialResult: String, done: Boolean) {
                    runOnUiThread {
                        val inferenceResult = JSONObject().apply {
                            put("type", "MODEL_INFERENCE_CHUNK")
                            put("chunk", partialResult)
                            put("done", done)
                        }
                        if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.M) {
                            nativePort?.postMessage(WebMessage(inferenceResult.toString()))
                        }
                    }
                }

                override fun onError(errorMessage: String) {
                    runOnUiThread {
                        val errorResult = JSONObject().apply {
                            put("type", "MODEL_INFERENCE_ERROR")
                            put("error", errorMessage)
                        }
                        if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.M) {
                            nativePort?.postMessage(WebMessage(errorResult.toString()))
                        }
                    }
                }
            })
        }

        @JavascriptInterface
        fun stopModelResponse() {
            activeModelHelper?.stopResponse()
        }

        @JavascriptInterface
        fun triggerWormholeTransfer(assetId: String, targetX: Int, targetY: Int) {
            // Logic to forward to Go Kernel via runner methods if needed
            Log.d("ButlerBridge", "Wormhole Triggered for $assetId")
        }

        @JavascriptInterface
        fun callSkill(skillId: String, action: String, paramsJson: String) {
            skillExecutor.execute {
                try {
                    val resultJson = butlerModule?.callAttr("call_plugin", skillId, action, paramsJson)?.toString()
                    if (resultJson != null) {
                        val result = JSONObject(resultJson)
                        if (result.optString("status") == "error") {
                            val errorType = result.optString("error_type")
                            val message = result.optString("message")
                            val traceback = result.optString("traceback")
                            Log.e("ButlerBridge", "Skill execution error ($errorType): $message\n$traceback")
                            // Report to Go Kernel
                            kernelRunner?.ReportError("PythonSkillError_$skillId", "[$errorType] $message", traceback)
                        } else {
                            Log.d("ButlerBridge", "Skill $skillId execution success: ${result.optString("data")}")
                        }
                    }
                } catch (e: Exception) {
                    val tb = Log.getStackTraceString(e)
                    Log.e("ButlerBridge", "Java/Kotlin bridge exception calling skill $skillId: ${e.message}", e)
                    kernelRunner?.ReportError("JavaBridgeError_$skillId", e.message ?: "Unknown error", tb)
                }
            }
        }
    }

    override fun onDestroy() {
        super.onDestroy()
        kernelRunner?.stop()
        butlerModule?.callAttr("cleanup")
        batteryReceiver?.let {
            unregisterReceiver(it)
        }
    }
}
